export async function onRequest(context) {
  const method = context.request.method;
  if (method !== 'GET' && method !== 'HEAD') return context.next();

  // Pages _headers rules do not apply to responses generated by Functions.
  // Fetch the static Owner shell without forwarding conditional request headers,
  // then explicitly enforce the app-shell cache policy for every asset status.
  const assetUrl = new URL('/admin.html', context.request.url);
  const assetRequest = new Request(assetUrl, { method: 'GET' });
  const assetResponse = await context.env.ASSETS.fetch(assetRequest);

  const headers = new Headers(assetResponse.headers);
  headers.set('cache-control', 'no-store, max-age=0, must-revalidate');

  return new Response(method === 'HEAD' ? null : assetResponse.body, {
    status: assetResponse.status,
    statusText: assetResponse.statusText,
    headers
  });
}
