(function(){
  const KEY='freshway-address-v2';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||null}catch(_){return null}};
  const write=v=>localStorage.setItem(KEY,JSON.stringify(v));
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  let current=read(), map=null, marker=null, mapReady=false, addresses=[];
  const $=s=>document.querySelector(s), field=id=>$('#'+id);
  const toast=msg=>{const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__addressToast);window.__addressToast=setTimeout(()=>t.classList.remove('show'),3000)};
  const setField=(id,v)=>{const el=field(id);if(el&&v!=null){el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))}};
  const getForm=()=>$('#checkoutForm');
  const addressFromFields=()=>({recipientName:field('customerName')?.value.trim()||'',deliveryPhone:field('customerPhone')?.value.trim()||'',houseFlat:field('house')?.value.trim()||'',area:field('area')?.value.trim()||'',city:field('city')?.value.trim()||'',pincode:field('pincode')?.value.trim()||'',landmark:field('landmark')?.value.trim()||'',note:field('note')?.value.trim()||'',...(current||{})});
  function displayAddress(a){const text=[a.houseFlat||a.house,a.area,a.locality,a.city].filter(Boolean).join(', ')+(a.pincode?` - ${a.pincode}`:'');const home=$('#homeAddress'),profile=$('#profileAddressText');if(home)home.textContent=text||'Add your delivery address';if(profile)profile.textContent=text||'Not saved yet'}
  function fill(a){if(!a)return;setField('customerName',a.recipientName);setField('customerPhone',a.deliveryPhone);setField('house',a.houseFlat);setField('area',a.area);setField('city',a.city);setField('pincode',a.pincode);setField('landmark',a.landmark);setField('note',a.note);current={...a};write(current);displayAddress(current);updateMap();}
  function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();if(document.querySelector('script[data-fw-leaflet]')){const wait=setInterval(()=>{if(window.L){clearInterval(wait);resolve()}},50);setTimeout(()=>{clearInterval(wait);reject(new Error('Map could not load.'))},10000);return}const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.async=true;s.dataset.fwLeaflet='1';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Map could not load.'));document.head.appendChild(s)});}
  function initMap(){const el=$('#addressMap');if(!el||!window.L)return;map=L.map(el,{zoomControl:true,attributionControl:true}).setView([20.5937,78.9629],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);marker=L.marker([20.5937,78.9629],{draggable:true}).addTo(map);marker.on('dragend',async()=>{const p=marker.getLatLng();await chooseCoords(p.lat,p.lng,'Map pin')});mapReady=true;updateMap();setTimeout(()=>map.invalidateSize(),100);}
  async function reverse(lat,lon){const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&zoom=18&lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Could not read this map location.');const d=await r.json();return d.address||{};}
  function mapAddress(a){const house=[a.house_number,a.building].filter(Boolean).join(' ').trim();const area=[a.road,a.neighbourhood,a.suburb].filter(Boolean).filter((v,i,x)=>x.indexOf(v)===i).slice(0,2).join(', ');return {houseFlat:house,area,locality:a.city_district||a.locality||a.suburb||'',city:a.city||a.town||a.village||a.municipality||'',district:a.district||a.county||'',state:a.state||'',pincode:a.postcode||'',landmark:a.amenity||a.shop||'',latitude:current?.latitude,longitude:current?.longitude}};
  async function chooseCoords(lat,lon,source){current={...(current||{}),latitude:Number(lat),longitude:Number(lon),locationSource:source,locationUpdatedAt:new Date().toISOString()};write(current);if(marker){marker.setLatLng([lat,lon]);map.setView([lat,lon],17)}try{const a=await reverse(lat,lon);const m=mapAddress(a);Object.assign(current,m,{latitude:Number(lat),longitude:Number(lon),locationSource:source});write(current);fill(current);toast('Location selected. Check the address details.')}catch(_){toast('Pin saved. Please complete the address details manually.')}renderStatus();}
  function updateMap(){if(!mapReady||!current?.latitude||!current?.longitude)return;marker.setLatLng([current.latitude,current.longitude]);map.setView([current.latitude,current.longitude],17);renderStatus()}
  function renderStatus(){const s=$('#addressLocationStatus');if(!s)return;if(current?.latitude!=null){const acc=current.accuracyMeters?` · ±${Math.round(current.accuracyMeters)} m`:'';s.innerHTML=`<div><strong>📍 Exact delivery location selected</strong><small>Pin is the delivery source of truth${acc}.</small></div><button type="button" class="secondary-btn" id="changeAddressLocation" style="flex:0 0 auto">Change</button>`}else{s.innerHTML='<div><strong>📍 Location not selected</strong><small>You can use GPS, search, or place the pin manually.</small></div>'}}
  async function locate(){if(!navigator.geolocation){toast('Location is not supported on this device.');return}const b=$('#fwUseGps');if(b){b.disabled=true;b.textContent='📍 Finding location…'}navigator.geolocation.getCurrentPosition(async p=>{try{current={...(current||{}),accuracyMeters:p.coords.accuracy};await chooseCoords(p.coords.latitude,p.coords.longitude,'GPS')}catch(e){toast(e.message||'Could not select your location.')}finally{if(b){b.disabled=false;b.textContent='📍 Use my current location'}}},e=>{toast(e.code===1?'Location permission was denied. You can enter the address manually.':'Could not determine your location. Please try again.');if(b){b.disabled=false;b.textContent='📍 Use my current location'}},{enableHighAccuracy:true,timeout:15000,maximumAge:30000})}
  async function searchLocation(){const q=prompt('Search delivery location');if(!q)return;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=in&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});const list=await r.json();if(!list.length){toast('No location found. Try a nearby landmark or locality.');return}const pick=list[0];await chooseCoords(Number(pick.lat),Number(pick.lon),'Search')}catch(_){toast('Location search is unavailable. You can place the pin manually.')}}
  async function loadSaved(){try{const r=await fetch('/api/addresses',{credentials:'include'});if(!r.ok)return;const d=await r.json();addresses=Array.isArray(d.addresses)?d.addresses:[];renderSaved()}catch(_){} }
  function renderSaved(){const el=$('#addressSaved');if(!el)return;el.innerHTML=addresses.map(a=>`<button type="button" class="address-chip ${current?.id===a.id?'active':''}" data-fw-address="${a.id}">${a.label==='Home'?'🏠':a.label==='Work'?'💼':'📍'} ${esc(a.label)}</button>`).join('')||'<span class="muted">No saved addresses yet.</span>'}
  function ensureUI(){const form=getForm();if(!form)return;if(!$('#addressV2')){const box=document.createElement('div');box.id='addressV2';box.className='address-v2';box.innerHTML='<div class="address-saved" id="addressSaved"></div><div class="address-labels"><button type="button" class="address-label active" data-fw-label="Home">🏠 Home</button><button type="button" class="address-label" data-fw-label="Work">💼 Work</button><button type="button" class="address-label" data-fw-label="Other">📍 Other</button></div><div class="address-actions"><button type="button" class="secondary-btn" id="fwUseGps">📍 Use my current location</button><button type="button" class="secondary-btn" id="fwSearchLocation">🔎 Search location</button></div><div id="addressMap" class="address-map"></div><div id="addressLocationStatus" class="address-location-status"></div><p class="address-map-note">Your delivery pin is the exact location. You can edit the address text without moving the pin. Move the pin only when you want to change the delivery location.</p>';form.insertBefore(box,form.firstElementChild);box.querySelector('#fwUseGps').onclick=locate;box.querySelector('#fwSearchLocation').onclick=searchLocation;loadLeaflet().then(initMap).catch(()=>toast('Map is unavailable. Manual address entry is still supported.'));renderSaved();renderStatus();}
    const phoneLabel=[...form.querySelectorAll('label')].find(x=>x.querySelector('#customerPhone'));if(phoneLabel&&!phoneLabel.dataset.fwPhone){phoneLabel.firstChild.textContent='Delivery contact number ';const small=document.createElement('small');small.textContent='Can be different from your registered mobile number.';small.style.cssText='display:block;color:#708078;font-weight:500;margin-top:4px';phoneLabel.insertBefore(small,phoneLabel.querySelector('input'));phoneLabel.dataset.fwPhone='1'}
  }
  function openManager(){const modal=$('#addressModal');if(!modal)return;modal.innerHTML='<div class="modal-sheet"><div class="modal-head"><div><span class="eyebrow">DELIVERY</span><h2>Your saved addresses</h2></div><button class="icon-btn" data-close-modal aria-label="Close">×</button></div><div id="addressManagerList"></div><button class="primary-btn full" id="addressManagerNew">+ Add address</button></div>';modal.classList.remove('hidden');renderManager();}
  function renderManager(){const el=$('#addressManagerList');if(!el)return;el.innerHTML=addresses.map(a=>`<article class="order-card" style="margin-top:10px"><div class="order-head"><strong>${a.label==='Home'?'🏠':a.label==='Work'?'💼':'📍'} ${esc(a.label)}</strong>${a.isDefault?'<span class="status delivered">Default</span>':''}</div><div class="address-block">${esc([a.houseFlat,a.area,a.locality,a.city].filter(Boolean).join(', '))}${a.pincode?` - ${esc(a.pincode)}`:''}</div><div class="order-actions"><button class="secondary-btn" data-fw-select="${a.id}">Use</button>${!a.isDefault?`<button class="secondary-btn" data-fw-default="${a.id}">Set default</button>`:''}<button class="secondary-btn danger" data-fw-delete="${a.id}">Delete</button></div></article>`).join('')||'<div class="empty" style="margin-top:10px">No saved addresses yet.</div>';}
  async function saveCurrent(){const a=addressFromFields();a.label=document.querySelector('.address-label.active')?.dataset.fwLabel||current?.label||'Other';a.latitude=current?.latitude??null;a.longitude=current?.longitude??null;a.accuracyMeters=current?.accuracyMeters??null;a.locationSource=current?.locationSource||'';a.placeId=current?.placeId||'';a.locationUpdatedAt=current?.locationUpdatedAt||'';if(!a.latitude||!a.longitude){toast('Please select your delivery location on the map or use your current location.');return}try{const r=await fetch('/api/addresses',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...a,isDefault:addresses.length===0})});if(!r.ok)throw new Error((await r.json()).error||'Could not save address.');const d=await r.json();addresses=d.addresses||[];current=addresses.find(x=>x.id===d.id)||a;write(current);displayAddress(current);toast('Address saved.');}catch(e){toast(e.message||'Could not save address.')}}
  document.addEventListener('click',async e=>{const t=e.target;if(t.closest('#addressBtn')||t.closest('#profileAddress')){e.preventDefault();e.stopImmediatePropagation();openManager();loadSaved();return}if(t.closest('[data-close-modal]')){$('#addressModal')?.classList.add('hidden');return}const chip=t.closest('[data-fw-address]');if(chip){const a=addresses.find(x=>String(x.id)===chip.dataset.fwAddress);if(a){fill(a);setTimeout(()=>$('#addressModal')?.classList.add('hidden'),100);}}const use=t.closest('[data-fw-select]');if(use){const a=addresses.find(x=>String(x.id)===use.dataset.fwSelect);if(a){fill(a);$('#addressModal')?.classList.add('hidden');}}const def=t.closest('[data-fw-default]');if(def){try{const r=await fetch(`/api/addresses/${def.dataset.fwDefault}/default`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(r.ok){addresses=d.addresses||[];renderManager();renderSaved();toast('Default address updated.')}}catch(_){toast('Could not update default address.')}}const del=t.closest('[data-fw-delete]');if(del&&confirm('Delete this saved address?')){try{const r=await fetch(`/api/addresses/${del.dataset.fwDelete}`,{method:'DELETE',credentials:'include'});const d=await r.json();if(r.ok){addresses=d.addresses||[];if(current?.id===Number(del.dataset.fwDelete)){current=addresses[0]||null;write(current)}renderManager();renderSaved();displayAddress(current);toast('Address deleted.')}}catch(_){toast('Could not delete address.')}}if(t.closest('#addressManagerNew')){$('#addressModal')?.classList.add('hidden');window.setView?.('checkout');setTimeout(ensureUI,50);}});
  document.addEventListener('change',e=>{const b=e.target.closest?.('[data-fw-label]');if(b){document.querySelectorAll('.address-label').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(current)current.label=b.dataset.fwLabel;}});
  document.addEventListener('click',e=>{if(e.target.closest('#changeAddressLocation')){toast('Use GPS, search, or drag the pin to change the location.')}});
  const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init){const url=typeof input==='string'?input:input?.url||'';if(String(url).endsWith('/api/orders')&&init?.method==='POST'&&init.body){try{const payload=JSON.parse(init.body);payload.address={...(payload.address||{}),...(current||{}),recipientName:field('customerName')?.value.trim()||payload.customer?.name||'',deliveryPhone:field('customerPhone')?.value.trim()||'',houseFlat:field('house')?.value.trim()||'',area:field('area')?.value.trim()||'',city:field('city')?.value.trim()||'',pincode:field('pincode')?.value.trim()||'',landmark:field('landmark')?.value.trim()||'',note:field('note')?.value.trim()||''};init={...init,body:JSON.stringify(payload)}}catch(_){}const res=await nativeFetch(input,init);if(res.ok){try{const copy=res.clone();const data=await copy.json();if(data?.id){await saveCurrent()}}catch(_){}}return res}return nativeFetch(input,init)};
  const observer=new MutationObserver(()=>{ensureUI();if(current)displayAddress(current)});observer.observe(document.body,{childList:true,subtree:true});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensureUI();if(current)fill(current);loadSaved()},{once:true});else{ensureUI();if(current)fill(current);loadSaved()}
})();
