const TOKEN_KEY='freshway-admin-token';
let token=sessionStorage.getItem(TOKEN_KEY)||'';let orders=[];let products=[];let filter='all',paymentFilter='all';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const api=async(path,options={})=>{const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data};
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);setTimeout(()=>t.classList.remove('show'),2400)}
function setAuthState(connected){$('#authState').textContent=connected?'Connected':'Not connected';$('#authState').classList.toggle('connected',connected)}
function saveToken(){token=$('#adminToken').value.trim();if(!token){toast('Enter the Worker ADMIN_TOKEN');return}sessionStorage.setItem(TOKEN_KEY,token);setAuthState(true);loadData()}
function metrics(){const o=orders;$('#mNew').textContent=o.filter(x=>x.status==='Ordered').length;$('#mPending').textContent=o.filter(x=>!['Delivered','Cancelled'].includes(x.status)).length;$('#mDelivered').textContent=o.filter(x=>x.status==='Delivered').length;$('#mCash').textContent=money(o.filter(x=>x.payment!=='Collected').reduce((s,x)=>s+x.total,0))}
function statusClass(s){return String(s||'').toLowerCase()}
function renderOrders(){let list=orders.slice();if(filter!=='all')list=list.filter(o=>o.status===filter);if(paymentFilter!=='all')list=list.filter(o=>paymentFilter==='pending'?o.payment!=='Collected':o.payment==='Collected');$('#resultCount').textContent=`${list.length} orders`;$('#ordersList').innerHTML=list.length?list.map(o=>`<article class="order-card"><div class="order-top"><div><strong>${o.id}</strong><div class="date">${new Date(o.createdAt).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}</div></div><span class="status ${statusClass(o.status)}">${o.status}</span></div><div class="customer"><div><strong>${o.customer.name}</strong><small>📞 ${o.customer.phone}</small></div><a class="action" href="tel:${o.customer.phone}">CALL</a></div><div class="items">${o.items.map(i=>`<div class="item"><span>${i.name} · ${i.qty} ${i.unit}</span><strong>${money(i.lineTotal??i.qty*i.price)}</strong></div>`).join('')}</div><div class="row" style="margin-top:10px;font-weight:900;font-size:12px"><span>Total</span><span>${money(o.total)}</span></div><div class="address">📍 ${o.address.house}, ${o.address.area}, ${o.address.city} - ${o.address.pincode}${o.address.landmark?`<br>Landmark: ${o.address.landmark}`:''}${o.address.note?`<br>Note: ${o.address.note}`:''}</div><div class="cash ${o.payment==='Collected'?'collected':'pending'}"><span>💵 Cash payment</span><strong>${o.payment}</strong></div><div class="actions">${o.status!=='Delivered'&&o.status!=='Cancelled'?`<button class="action primary-action" data-deliver="${o.id}">✓ Mark delivered</button>`:''}${o.payment!=='Collected'?`<button class="action" data-paid="${o.id}">₹ Mark cash collected</button>`:`<button class="action" disabled>✓ Cash collected</button>`}${o.status==='Ordered'?`<button class="action" data-process="${o.id}">Start processing</button>`:''}${o.status!=='Cancelled'&&o.status!=='Delivered'?`<button class="action danger-action" data-cancel="${o.id}">Cancel order</button>`:''}<button class="action" data-map="${encodeURIComponent(`${o.address.house}, ${o.address.area}, ${o.address.city}, ${o.address.pincode}`)}">Open map</button></div></article>`).join(''):'<div class="empty" style="grid-column:1/-1;background:#fff;border:1px dashed #ccd9d1;border-radius:16px;padding:35px;text-align:center;color:#718078"><strong>No orders in this view</strong><br>New customer orders will appear here.</div>'}
function renderProducts(){$('#productList').innerHTML=products.map(p=>`<div class="product-admin"><div class="emoji">${p.emoji}</div><strong>${p.name}</strong><small>${p.unit} · <span class="price">${money(p.price)}</span></small><div style="margin-top:8px;font-size:9px;color:${p.active?'#0f7a4b':'#b83d3d'}">● ${p.active?'Available':'Hidden'}</div><div class="product-admin-actions"><button class="action" data-toggle-product="${p.id}" data-active="${p.active}">${p.active?'Hide':'Show'}</button><button class="action" data-edit-product="${p.id}">Edit price</button></div></div>`).join('')||'<div class="empty">No products yet.</div>'}
async function loadData(){if(!token){setAuthState(false);return}try{const [orderData,productData]=await Promise.all([api('/api/admin/orders'),api('/api/admin/products')]);orders=orderData.orders||[];products=productData.products||[];metrics();renderOrders();renderProducts();setAuthState(true)}catch(error){if(/Unauthorized/i.test(error.message)){sessionStorage.removeItem(TOKEN_KEY);token='';setAuthState(false)}toast(error.message)}}
async function updateOrder(id,patch){try{await api(`/api/admin/orders/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(patch)});await loadData();toast(`${id} updated`)}catch(error){toast(error.message)}}
async function updateProduct(id,patch){try{await api(`/api/admin/products/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(patch)});await loadData();toast('Product updated')}catch(error){toast(error.message)}}
async function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const raw=prompt(`New price for ${p.name}`,p.price);if(raw===null)return;const price=Number(raw);if(!Number.isFinite(price)||price<0){toast('Enter a valid price');return}updateProduct(id,{price})}
async function sendNotification(){if(!token){toast('Connect the dashboard first');return}const channels=[];if($('#channelApp').checked)channels.push('app');if($('#channelWhatsapp').checked)channels.push('whatsapp');if(!channels.length){toast('Select at least one channel');return}const title=$('#notifyTitle').value.trim();const body=$('#notifyBody').value.trim();if(!title||!body){toast('Enter title and message');return}if(channels.includes('whatsapp')&&!$('#waTemplate').value.trim()){toast('WhatsApp needs an approved template name');return}const button=$('#sendNotificationBtn');button.disabled=true;button.textContent='Sending…';try{const payload={channels,title,body,url:'/',tag:`broadcast-${Date.now()}`};if(channels.includes('whatsapp')){payload.templateName=$('#waTemplate').value.trim();payload.languageCode=$('#waLanguage').value.trim()||'en_US';payload.parameters=$('#waParams').value.split(',').map(x=>x.trim()).filter(Boolean)}const data=await api('/api/notifications/broadcast',{method:'POST',body:JSON.stringify(payload)});toast((data.results||[]).map(x=>`${x.channel}: ${x.success}/${x.recipients}`).join(' · ')||'Sent')}catch(error){toast(error.message||'Could not send notification')}finally{button.disabled=false;button.textContent='Send to selected customers'}}
async function addProduct(e){e.preventDefault();if(!token){toast('Connect the dashboard first');return}const payload={name:$('#pName').value.trim(),price:Number($('#pPrice').value),unit:$('#pUnit').value.trim(),emoji:$('#pEmoji').value||'🍎'};try{await api('/api/admin/products',{method:'POST',body:JSON.stringify(payload)});e.target.reset();$('#pEmoji').value='🍎';$('#productModal').classList.add('hidden');await loadData();toast('Product added')}catch(error){toast(error.message)}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter!==undefined){filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderOrders()}if(b.dataset.payment!==undefined){paymentFilter=b.dataset.payment;$$('[data-payment]').forEach(x=>x.classList.toggle('active',x===b));renderOrders()}if(b.dataset.deliver)updateOrder(b.dataset.deliver,{status:'Delivered'});if(b.dataset.paid)updateOrder(b.dataset.paid,{payment:'Collected'});if(b.dataset.process)updateOrder(b.dataset.process,{status:'Processing'});if(b.dataset.cancel&&confirm(`Cancel ${b.dataset.cancel}?`))updateOrder(b.dataset.cancel,{status:'Cancelled'});if(b.dataset.toggleProduct)updateProduct(b.dataset.toggleProduct,{active:b.dataset.active!=='1'});if(b.dataset.editProduct)editProduct(b.dataset.editProduct);if(b.dataset.map)window.open(`https://www.google.com/maps/search/?api=1&query=${b.dataset.map}`,'_blank');if(b.id==='refreshBtn')loadData();if(b.id==='connectBtn')saveToken();if(b.id==='addProductBtn')$('#productModal').classList.remove('hidden');if(b.id==='sendNotificationBtn')sendNotification();if(b.hasAttribute('data-close'))$('#productModal').classList.add('hidden')});
$('#adminToken').value=token;setAuthState(!!token);$('#channelWhatsapp').addEventListener('change',e=>$('#whatsappFields').classList.toggle('hidden',!e.target.checked));$('#productForm').addEventListener('submit',addProduct);loadData();
