const FALLBACK_PRODUCTS=[
  {id:'apple',name:'Apple',unit:'kg',price:120,emoji:'🍎'},
  {id:'banana',name:'Banana',unit:'dozen',price:60,emoji:'🍌'},
  {id:'mango',name:'Mango',unit:'kg',price:180,emoji:'🥭'},
  {id:'orange',name:'Orange',unit:'kg',price:100,emoji:'🍊'},
  {id:'watermelon',name:'Watermelon',unit:'piece',price:50,emoji:'🍉'},
  {id:'grapes',name:'Grapes',unit:'kg',price:110,emoji:'🍇'},
  {id:'pineapple',name:'Pineapple',unit:'piece',price:70,emoji:'🍍'},
  {id:'guava',name:'Guava',unit:'kg',price:90,emoji:'🍐'},
  {id:'papaya',name:'Papaya',unit:'piece',price:80,emoji:'🧡'},
  {id:'pomegranate',name:'Pomegranate',unit:'kg',price:160,emoji:'❤️'}
];
const KEY='freshway-state-v2';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{cart:{},orders:[],profile:{address:''}};
let PRODUCTS=FALLBACK_PRODUCTS.slice();
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const api=async(path,options={})=>{const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'FreshWay server is unavailable.');return data};
const customerId=()=>FreshWayNotifications.customerId();
const cartItems=()=>Object.entries(state.cart).map(([id,qty])=>({product:PRODUCTS.find(p=>p.id===id),qty})).filter(x=>x.product&&x.qty>0);
const cartTotal=()=>cartItems().reduce((s,x)=>s+x.product.price*x.qty,0);const cartCount=()=>cartItems().reduce((s,x)=>s+x.qty,0);
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function formatDate(value){const d=new Date(value);return Number.isNaN(d.getTime())?String(value||''):d.toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function planText(plan){return plan==='Today'?'Today':plan==='Tomorrow'?'Tomorrow':plan==='Later'?'Later':plan==='Unscheduled'?'To be planned':'Planned'}
function renderProducts(filter=''){const grid=$('#productGrid');if(!grid)return;const q=filter.trim().toLowerCase();const list=PRODUCTS.filter(p=>p.active!==0&&p.name.toLowerCase().includes(q));grid.innerHTML=list.map(p=>{const qty=state.cart[p.id]||0;return `<article class="product-card"><div class="product-image">${esc(p.emoji)}</div><h3>${esc(p.name)}</h3><div class="product-meta">Fresh today · ${esc(p.unit)}</div><div class="product-actions"><span class="product-price">${money(p.price)}<small>/${esc(p.unit)}</small></span>${qty?`<div class="qty-control"><button data-minus="${esc(p.id)}">−</button><span>${qty}</span><button data-plus="${esc(p.id)}">+</button></div>`:`<button class="add-btn" data-add="${esc(p.id)}">ADD</button>`}</div></article>`}).join('')||`<div class="empty" style="grid-column:1/-1"><strong>No products found</strong>Try another search.</div>`;updateCartBar()}
function updateCartBar(){const n=cartCount();const count=$('#cartCount');const total=$('#cartTotal');const badge=$('#cartBadge');const bar=$('#cartBar');const checkout=$('#checkoutTotal');if(count)count.textContent=`${n} ${n===1?'item':'items'}`;if(total)total.textContent=money(cartTotal());if(badge){badge.textContent=n;badge.classList.toggle('hidden',!n)}if(bar)bar.classList.toggle('hidden',!n);if(checkout)checkout.textContent=money(cartTotal())}
function renderCart(){const items=cartItems();const cartItemsEl=$('#cartItems');const summary=$('#cartSummary');if(!cartItemsEl||!summary)return;if(!items.length){cartItemsEl.innerHTML='<div class="empty"><div style="font-size:38px">🛒</div><strong>Your cart is empty</strong>Add some fresh products to continue.</div>';summary.innerHTML='';return}cartItemsEl.innerHTML=items.map(x=>`<article class="order-card"><div class="order-head"><strong>${esc(x.product.emoji)} ${esc(x.product.name)}</strong><strong>${money(x.product.price*x.qty)}</strong></div><div class="order-items"><div class="order-line"><span>${x.qty} × ${esc(x.product.unit)}</span><span>${money(x.product.price)} / ${esc(x.product.unit)}</span></div></div><div class="product-actions"><span class="product-meta" style="margin:0">Quantity</span><div class="qty-control"><button data-minus="${esc(x.product.id)}">−</button><span>${x.qty}</span><button data-plus="${esc(x.product.id)}">+</button></div></div></article>`).join('');summary.innerHTML=`<div class="summary-line"><span>Products</span><strong>${money(cartTotal())}</strong></div><div class="summary-line"><span>Delivery</span><strong>Offline delivery</strong></div><div class="summary-line total"><span>Total</span><span>${money(cartTotal())}</span></div><button class="primary-btn full" id="checkoutBtn">Continue to address</button>`}
function renderOrders(list=state.orders){const el=$('#customerOrders');if(!el)return;if(!list.length){el.innerHTML='<div class="empty"><div style="font-size:38px">📦</div><strong>No orders yet</strong>Your placed orders will appear here.</div>';return}el.innerHTML=list.map(o=>`<article class="order-card"><div class="order-head"><strong>${esc(o.id)}</strong><span class="status ${String(o.status).toLowerCase()}">${esc(o.status)}</span></div><div class="order-date">${esc(formatDate(o.createdAt))}</div><div class="order-items">${o.items.map(i=>`<div class="order-line"><span>${esc(i.name)} · ${i.qty} ${esc(i.unit)}</span><strong>${money(i.lineTotal??i.price*i.qty)}</strong></div>`).join('')}</div><div class="order-total"><span>Total</span><span>${money(o.total)}</span></div><div class="address-block">📍 ${esc(o.address.house)}, ${esc(o.address.area)}, ${esc(o.address.city)} - ${esc(o.address.pincode)}${o.address.landmark?`<br>Landmark: ${esc(o.address.landmark)}`:''}</div><div class="status-row"><span class="product-meta" style="margin:0">🚚 Delivery plan</span><span class="status ordered">${esc(planText(o.deliveryPlan))}</span></div><div class="status-row"><span class="product-meta" style="margin:0">💵 Cash payment</span><span class="status ${o.payment==='Collected'?'delivered':'ordered'}">${esc(o.payment)}</span></div></article>`).join('')}
async function loadOrders(){try{const data=await api(`/api/orders?customerId=${encodeURIComponent(customerId())}`);state.orders=data.orders||[];save();renderOrders(state.orders)}catch(_){renderOrders(state.orders);if(state.orders.length)toast('Showing saved orders from this device.')}}
function setView(name){$('#confirmationView')?.remove();$$('.view').forEach(v=>v.classList.remove('active-view'));const view=$(`#${name}View`);if(!view)return;view.classList.add('active-view');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='cart')renderCart();if(name==='orders'){renderOrders();loadOrders()}if(name==='profile')renderProfile();window.scrollTo({top:0,behavior:'smooth'})}
function renderProfile(){const name=$('#profileName'),phone=$('#profilePhone'),addr=$('#profileAddressText'),home=$('#homeAddress');const last=state.orders.at(-1);if(name)name.textContent=last?.customer.name||'Guest customer';if(phone)phone.textContent=last?.customer.phone||'Place an order to save your details';if(addr)addr.textContent=state.profile.address||'Not saved yet';if(home)home.textContent=state.profile.address||'Add your delivery address'}
function changeQty(id,delta){state.cart[id]=(state.cart[id]||0)+delta;if(state.cart[id]<=0)delete state.cart[id];save();const search=$('#searchInput');renderProducts(search?.value||'');if($('#cartView')?.classList.contains('active-view'))renderCart()}
function openAddressModal(){const saved=$('#savedAddress'),modal=$('#addressModal');if(saved)saved.value=state.profile.address||'';modal?.classList.remove('hidden')}function closeModal(){$('#addressModal')?.classList.add('hidden')}
async function submitOrder(e){e.preventDefault();if(!cartItems().length){toast('Your cart is empty');setView('home');return}const form=e.target;const nameEl=$('#customerName'),phoneEl=$('#customerPhone');const data={name:nameEl?.value.trim()||'',phone:phoneEl?.value.trim()||''};const address={house:$('#house')?.value.trim()||'',area:$('#area')?.value.trim()||'',city:$('#city')?.value.trim()||'',pincode:$('#pincode')?.value.trim()||'',landmark:$('#landmark')?.value.trim()||'',note:$('#note')?.value.trim()||''};if(!/^[0-9]{10}$/.test(data.phone)){toast('Enter a valid 10-digit mobile number');return}const whatsappOptIn=$('#whatsappOptIn')?.checked||false;const button=form.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Placing order…'}try{const result=await api('/api/orders',{method:'POST',body:JSON.stringify({customerId:customerId(),customer:data,address,items:cartItems().map(x=>({id:x.product.id,qty:x.qty})),whatsappOptIn})});const order={id:result.id,customer:data,address,items:result.items.map(i=>({name:i.name,unit:i.unit,qty:i.qty,price:i.price,lineTotal:i.lineTotal})),total:result.total,payment:result.payment,status:result.status,deliveryPlan:result.deliveryPlan,createdAt:result.createdAt,updatedAt:result.updatedAt};state.orders=[...state.orders.filter(x=>x.id!==order.id),order];state.cart={};state.profile.address=`${address.house}, ${address.area}, ${address.city} - ${address.pincode}`;save();await FreshWayNotifications.registerCustomer(data.name,data.phone,whatsappOptIn);if(form)form.reset();const city=$('#city');if(city)city.value='Hyderabad';renderProducts();renderProfile();showConfirmation(order)}catch(error){toast(error.message||'Could not place order. Your cart is still saved.')}finally{if(button){button.disabled=false;button.innerHTML='Place order · <span id="checkoutTotal">'+money(cartTotal())+'</span>'}updateCartBar()}}
function showConfirmation(order){const home=$('#homeView');if(!home)return;$('#confirmationView')?.remove();home.insertAdjacentHTML('afterend',`<section id="confirmationView" class="view active-view"><div class="empty" style="margin-top:20vh"><div style="font-size:55px">🎉</div><span class="eyebrow">ORDER PLACED</span><h1 style="font-size:25px;margin:8px 0">Thank you!</h1><p>Your order <strong>${esc(order.id)}</strong> has been placed successfully.</p><p class="muted">Payment: Cash · Delivery plan: ${esc(planText(order.deliveryPlan))}.</p><button class="primary-btn full" id="confirmationOrders">View my orders</button><button class="secondary-btn full" id="confirmationHome">Continue shopping</button></div></section>`);$$('.view').forEach(v=>{if(v.id!=='confirmationView')v.classList.remove('active-view')});$$('.nav-item').forEach(b=>b.classList.remove('active'));const orders=$('#confirmationOrders'),homeBtn=$('#confirmationHome');if(orders)orders.onclick=()=>setView('orders');if(homeBtn)homeBtn.onclick=()=>setView('home');updateCartBar()}
async function loadProducts(){try{const data=await api('/api/products');if(Array.isArray(data.products)&&data.products.length)PRODUCTS=data.products;renderProducts($('#searchInput')?.value||'')}catch(_){renderProducts($('#searchInput')?.value||'')}}
document.addEventListener('click',e=>{const t=e.target;if(t.closest('[data-add]')){changeQty(t.closest('[data-add]').dataset.add,1);toast('Added to cart')}if(t.closest('[data-plus]'))changeQty(t.closest('[data-plus]').dataset.plus,1);if(t.closest('[data-minus]'))changeQty(t.closest('[data-minus]').dataset.minus,-1);const nav=t.closest('[data-nav]');if(nav)setView(nav.dataset.nav);if(t.id==='viewCartBtn')setView('cart');if(t.id==='checkoutBtn')setView('checkout');if(t.id==='addressBtn'||t.id==='profileAddress')openAddressModal();if(t.hasAttribute('data-close-modal'))closeModal();if(t.id==='saveAddressBtn'){const v=$('#savedAddress')?.value.trim();if(!v){toast('Please enter your address');return}state.profile.address=v;save();renderProfile();closeModal();toast('Address saved')}if(t.id==='profileBtn')setView('profile');if(t.id==='brandHome')setView('home');if(t.classList.contains('back-btn'))setView(t.dataset.back)});
const searchInput=$('#searchInput');if(searchInput)searchInput.addEventListener('input',e=>renderProducts(e.target.value));const checkoutForm=$('#checkoutForm');if(checkoutForm)checkoutForm.addEventListener('submit',submitOrder);renderProducts();renderProfile();updateCartBar();loadProducts();loadOrders();