const PRODUCTS = [
  {id:'apple',name:'Apple',unit:'kg',price:120,emoji:'🍎'},
  {id:'banana',name:'Banana',unit:'dozen',price:60,emoji:'🍌'},
  {id:'mango',name:'Mango',unit:'kg',price:180,emoji:'🥭'},
  {id:'orange',name:'Orange',unit:'kg',price:100,emoji:'🍊'},
  {id:'watermelon',name:'Watermelon',unit:'piece',price:50,emoji:'🍉'},
  {id:'grapes',name:'Grapes',unit:'kg',price:110,emoji:'🍇'},
  {id:'pineapple',name:'Pineapple',unit:'piece',price:70,emoji:'🍍'},
  {id:'guava',name:'Guava',unit:'kg',price:90,emoji:'🍐'},
  {id:'papaya',name:'Papaya',unit:'piece',price:80,emoji:'🧡'},
  {id:'pomegranate',name:'Pomegranate',unit:'kg',price:160,emoji:'❤️'}
];
const KEY='freshway-state-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{cart:{},orders:[],profile:{address:''}};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const money=n=>`₹${Number(n).toLocaleString('en-IN')}`;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const cartItems=()=>Object.entries(state.cart).map(([id,qty])=>({product:PRODUCTS.find(p=>p.id===id),qty})).filter(x=>x.product&&x.qty>0);
const cartTotal=()=>cartItems().reduce((s,x)=>s+x.product.price*x.qty,0);
const cartCount=()=>cartItems().reduce((s,x)=>s+x.qty,0);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function renderProducts(filter=''){
  const q=filter.trim().toLowerCase();
  const list=PRODUCTS.filter(p=>p.name.toLowerCase().includes(q));
  $('#productGrid').innerHTML=list.map(p=>{const qty=state.cart[p.id]||0;return `<article class="product-card"><div class="product-image">${p.emoji}</div><h3>${p.name}</h3><div class="product-meta">Fresh today · ${p.unit}</div><div class="product-actions"><span class="product-price">${money(p.price)}<small>/${p.unit}</small></span>${qty?`<div class="qty-control"><button data-minus="${p.id}">−</button><span>${qty}</span><button data-plus="${p.id}">+</button></div>`:`<button class="add-btn" data-add="${p.id}">ADD</button>`}</div></article>`}).join('')||`<div class="empty" style="grid-column:1/-1"><strong>No products found</strong>Try another search.</div>`;
  updateCartBar();
}
function updateCartBar(){const n=cartCount();$('#cartCount').textContent=`${n} ${n===1?'item':'items'}`;$('#cartTotal').textContent=money(cartTotal());$('#cartBadge').textContent=n;$('#cartBadge').classList.toggle('hidden',!n);$('#cartBar').classList.toggle('hidden',!n);$('#checkoutTotal').textContent=money(cartTotal())}
function renderCart(){const items=cartItems();if(!items.length){$('#cartItems').innerHTML='<div class="empty"><div style="font-size:38px">🛒</div><strong>Your cart is empty</strong>Add some fresh products to continue.</div>';$('#cartSummary').innerHTML='';return}$('#cartItems').innerHTML=items.map(x=>`<article class="order-card"><div class="order-head"><strong>${x.product.emoji} ${x.product.name}</strong><strong>${money(x.product.price*x.qty)}</strong></div><div class="order-items"><div class="order-line"><span>${x.qty} × ${x.product.unit}</span><span>${money(x.product.price)} / ${x.product.unit}</span></div></div><div class="product-actions"><span class="product-meta" style="margin:0">Quantity</span><div class="qty-control"><button data-minus="${x.product.id}">−</button><span>${x.qty}</span><button data-plus="${x.product.id}">+</button></div></div></article>`).join('');$('#cartSummary').innerHTML=`<div class="summary-line"><span>Products</span><strong>${money(cartTotal())}</strong></div><div class="summary-line"><span>Delivery</span><strong>Offline delivery</strong></div><div class="summary-line total"><span>Total</span><span>${money(cartTotal())}</span></div><button class="primary-btn full" id="checkoutBtn">Continue to address</button>`}
function renderOrders(){const list=state.orders;if(!list.length){$('#customerOrders').innerHTML='<div class="empty"><div style="font-size:38px">📦</div><strong>No orders yet</strong>Your placed orders will appear here.</div>';return}$('#customerOrders').innerHTML=list.slice().reverse().map(o=>`<article class="order-card"><div class="order-head"><strong>${o.id}</strong><span class="status ${o.status.toLowerCase()}">${o.status}</span></div><div class="order-date">${o.createdAt}</div><div class="order-items">${o.items.map(i=>`<div class="order-line"><span>${i.name} · ${i.qty} ${i.unit}</span><strong>${money(i.price*i.qty)}</strong></div>`).join('')}</div><div class="order-total"><span>Total</span><span>${money(o.total)}</span></div><div class="address-block">📍 ${o.address.house}, ${o.address.area}, ${o.address.city} - ${o.address.pincode}${o.address.landmark?`<br>Landmark: ${o.address.landmark}`:''}</div><div class="status-row"><span class="product-meta" style="margin:0">💵 Cash payment</span><span class="status ${o.payment==='Collected'?'delivered':'ordered'}">${o.payment}</span></div></article>`).join('')}
function setView(name){$$('.view').forEach(v=>v.classList.remove('active-view'));$(`#${name}View`).classList.add('active-view');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='cart')renderCart();if(name==='orders')renderOrders();if(name==='profile')renderProfile();window.scrollTo({top:0,behavior:'smooth'})}
function renderProfile(){const last=state.orders.at(-1);$('#profileName').textContent=last?.customer.name||'Guest customer';$('#profilePhone').textContent=last?.customer.phone||'Place an order to save your details';$('#profileAddressText').textContent=state.profile.address||'Not saved yet';$('#homeAddress').textContent=state.profile.address||'Add your delivery address'}
function changeQty(id,delta){state.cart[id]=(state.cart[id]||0)+delta;if(state.cart[id]<=0)delete state.cart[id];save();renderProducts($('#searchInput').value);if($('#cartView').classList.contains('active-view'))renderCart()}
function openAddressModal(){$('#savedAddress').value=state.profile.address||'';$('#addressModal').classList.remove('hidden')}
function closeModal(){$('#addressModal').classList.add('hidden')}
function submitOrder(e){e.preventDefault();const form=e.target;const data={name:$('#customerName').value.trim(),phone:$('#customerPhone').value.trim()};const address={house:$('#house').value.trim(),area:$('#area').value.trim(),city:$('#city').value.trim(),pincode:$('#pincode').value.trim(),landmark:$('#landmark').value.trim(),note:$('#note').value.trim()};if(!/^[0-9]{10}$/.test(data.phone)){toast('Enter a valid 10-digit mobile number');return}const order={id:`FW-${String(Date.now()).slice(-6)}`,customer:data,address,items:cartItems().map(x=>({name:x.product.name,unit:x.product.unit,qty:x.qty,price:x.product.price})),total:cartTotal(),payment:'Pending',status:'Ordered',createdAt:new Date().toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}),updatedAt:Date.now()};state.orders.push(order);state.cart={};state.profile.address=`${address.house}, ${address.area}, ${address.city} - ${address.pincode}`;save();form.reset();$('#city').value='Hyderabad';renderProducts();renderProfile();renderOrders();showConfirmation(order)}
function showConfirmation(order){$('#homeView').insertAdjacentHTML('afterend',`<section id="confirmationView" class="view active-view"><div class="empty" style="margin-top:20vh"><div style="font-size:55px">🎉</div><span class="eyebrow">ORDER PLACED</span><h1 style="font-size:25px;margin:8px 0">Thank you!</h1><p>Your order <strong>${order.id}</strong> has been placed successfully.</p><p class="muted">Payment: Cash · Delivery will be arranged offline.</p><button class="primary-btn full" id="confirmationOrders">View my orders</button><button class="secondary-btn full" id="confirmationHome">Continue shopping</button></div></section>`);$$('.view').forEach(v=>{if(v.id!=='confirmationView')v.classList.remove('active-view')});$$('.nav-item').forEach(b=>b.classList.remove('active'));$('#confirmationOrders').onclick=()=>{ $('#confirmationView').remove();setView('orders')};$('#confirmationHome').onclick=()=>{$('#confirmationView').remove();setView('home')};updateCartBar()}

document.addEventListener('click',e=>{const t=e.target;if(t.closest('[data-add]')){changeQty(t.closest('[data-add]').dataset.add,1);toast('Added to cart')}if(t.closest('[data-plus]'))changeQty(t.closest('[data-plus]').dataset.plus,1);if(t.closest('[data-minus]'))changeQty(t.closest('[data-minus]').dataset.minus,-1);const nav=t.closest('[data-nav]');if(nav)setView(nav.dataset.nav);if(t.id==='viewCartBtn')setView('cart');if(t.id==='checkoutBtn')setView('checkout');if(t.id==='addressBtn'||t.id==='profileAddress')openAddressModal();if(t.hasAttribute('data-close-modal'))closeModal();if(t.id==='saveAddressBtn'){const v=$('#savedAddress').value.trim();if(!v){toast('Please enter your address');return}state.profile.address=v;save();renderProfile();closeModal();toast('Address saved')}if(t.id==='profileBtn')setView('profile');if(t.id==='brandHome')setView('home');if(t.classList.contains('back-btn'))setView(t.dataset.back);});
$('#searchInput').addEventListener('input',e=>renderProducts(e.target.value));$('#checkoutForm').addEventListener('submit',submitOrder);renderProducts();renderProfile();updateCartBar();
