const FALLBACK_PRODUCTS=[
  {id:'apple',name:'Apple',unit:'kg',price:120,emoji:'🍎'},
  {id:'banana',name:'Banana',unit:'dozen',price:60,emoji:'🍌'},
  {id:'mango',name:'Mango',unit:'kg',price:180,emoji:'🥭'},
  {id:'orange',name:'Orange',unit:'kg',price:100,emoji:'🍊'},
  {id:'watermelon',name:'Watermelon',unit:'piece',price:50,emoji:'🍉'},
  {id:'grapes',name:'Grapes',unit:'kg',price:110,emoji:'🍇'},
  {id:'pineapple',name:'Pineapple',unit:'piece',price:70,emoji:'🍍'},
  {id:'guava',name:'Guava',unit:'kg',price:90,emoji:'🍐'},
  {id:'papaya',name:'Papaya',unit:'piece',price:80,emoji:'🧡'},
  {id:'pomegranate',name:'Pomegranate',unit:'kg',price:160,emoji:'❤️'}
];
const KEY='freshway-state-v2';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function initialState(){return{cart:{},orders:[],profile:{address:'',checkout:{}}}}
function readState(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(!p||typeof p!=='object')return initialState();return{cart:p.cart&&typeof p.cart==='object'?p.cart:{},orders:Array.isArray(p.orders)?p.orders:[],profile:{address:String(p.profile?.address||''),checkout:p.profile?.checkout&&typeof p.profile.checkout==='object'?p.profile.checkout:{}}}}catch(_){return initialState()}}
const state=readState();
let PRODUCTS=FALLBACK_PRODUCTS.slice();
let ordersRefreshTimer=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const api=async(path,options={})=>{const r=await fetch(path,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'FreshWay server is unavailable.');return d};
const customerId=()=>window.FreshWayNotifications?.customerId?.()||null;
const cartItems=()=>Object.entries(state.cart).map(([id,q])=>({product:PRODUCTS.find(p=>p.id===id),qty:Number(q)})).filter(x=>x.product&&Number.isInteger(x.qty)&&x.qty>0);
const cartTotal=()=>cartItems().reduce((s,x)=>s+x.product.price*x.qty,0);
const cartCount=()=>cartItems().reduce((s,x)=>s+x.qty,0);
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function formatDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?String(v||''):d.toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function planText(p){return p==='Today'?'Today':p==='Tomorrow'?'Tomorrow':p==='Later'?'Later':p==='Unscheduled'?'To be planned':'Planned'}
function renderProducts(filter=''){const grid=$('#productGrid');if(!grid)return;const q=String(filter).trim().toLowerCase();const list=PRODUCTS.filter(p=>p.active!==0&&String(p.name).toLowerCase().includes(q));const count=$('.count-pill');if(count)count.textContent=`${list.length} ${list.length===1?'item':'items'}`;grid.innerHTML=list.map(p=>{const qty=Number(state.cart[p.id]||0);return `<article class="product-card"><div class="product-image">${esc(p.emoji)}</div><h3>${esc(p.name)}</h3><div class="product-meta">Fresh today · ${esc(p.unit)}</div><div class="product-actions"><span class="product-price">${money(p.price)}<small>/${esc(p.unit)}</small></span>${qty?`<div class="qty-control"><button data-minus="${esc(p.id)}" aria-label="Remove one ${esc(p.name)}">−</button><span>${qty}</span><button data-plus="${esc(p.id)}" aria-label="Add one ${esc(p.name)}">+</button></div>`:`<button class="add-btn" data-add="${esc(p.id)}">ADD</button>`}</div></article>`}).join('')||'<div class="empty" style="grid-column:1/-1"><strong>No products found</strong><br>Try another search.</div>';updateCartBar()}
function updateCartBar(){const n=cartCount();const a=$('#cartCount'),b=$('#cartTotal'),c=$('#cartBadge'),bar=$('#cartBar'),t=$('#checkoutTotal');if(a)a.textContent=`${n} ${n===1?'item':'items'}`;if(b)b.textContent=money(cartTotal());if(c){c.textContent=n;c.classList.toggle('hidden',!n)}if(bar)bar.classList.toggle('hidden',!n);if(t)t.textContent=money(cartTotal())}
function renderCart(){const items=cartItems(),el=$('#cartItems'),sum=$('#cartSummary');if(!el||!sum)return;if(!items.length){el.innerHTML='<div class="empty"><div style="font-size:38px">🛒</div><strong>Your cart is empty</strong><br>Add some fresh products to continue.</div>';sum.innerHTML='';return}el.innerHTML=items.map(x=>`<article class="order-card"><div class="order-head"><strong>${esc(x.product.emoji)} ${esc(x.product.name)}</strong><strong>${money(x.product.price*x.qty)}</strong></div><div class="order-items"><div class="order-line"><span>${x.qty} × ${esc(x.product.unit)}</span><span>${money(x.product.price)} / ${esc(x.product.unit)}</span></div></div><div class="product-actions"><span class="product-meta" style="margin:0">Quantity</span><div class="qty-control"><button data-minus="${esc(x.product.id)}">−</button><span>${x.qty}</span><button data-plus="${esc(x.product.id)}">+</button></div></div></article>`).join('');sum.innerHTML=`<div class="summary-line"><span>Products</span><strong>${money(cartTotal())}</strong></div><div class="summary-line"><span>Delivery</span><strong>Offline delivery</strong></div><div class="summary-line total"><span>Total</span><span>${money(cartTotal())}</span></div><button class="primary-btn full" id="checkoutBtn">Continue to address</button>`}
function renderOrders(list=state.orders){const el=$('#customerOrders');if(!el)return;if(!list.length){el.innerHTML='<div class="empty"><div style="font-size:38px">📦</div><strong>No orders yet</strong><br>Your placed orders will appear here.</div>';return}el.innerHTML=list.map(o=>`<article class="order-card"><div class="order-head"><strong>${esc(o.id)}</strong><span class="status ${String(o.status||'').toLowerCase().replaceAll(' ','-')}">${esc(o.status||'')}</span></div><div class="order-date">${esc(formatDate(o.createdAt))}</div><div class="order-items">${(o.items||[]).map(i=>`<div class="order-line"><span>${esc(i.name)} · ${i.qty} ${esc(i.unit)}</span><strong>${money(i.lineTotal??i.price*i.qty)}</strong></div>`).join('')}</div><div class="order-total"><span>Total</span><span>${money(o.total)}</span></div><div class="address-block">📍 ${esc(o.address?.house||'')}, ${esc(o.address?.area||'')}, ${esc(o.address?.city||'')} - ${esc(o.address?.pincode||'')}${o.address?.landmark?`<br>Landmark: ${esc(o.address.landmark)}`:''}${o.address?.note?`<br>Note: ${esc(o.address.note)}`:''}</div><div class="status-row"><span class="product-meta" style="margin:0">🚚 Delivery plan</span><span class="status ordered">${esc(planText(o.deliveryPlan))}</span></div><div class="status-row"><span class="product-meta" style="margin:0">💵 Cash payment</span><span class="status ${o.payment==='Collected'?'delivered':'ordered'}">${esc(o.payment||'Pending')}</span></div></article>`).join('')}
async function loadOrders(){const id=customerId();if(!id){renderOrders(state.orders);return}try{const d=await api(`/api/orders?customerId=${encodeURIComponent(id)}`);if(Array.isArray(d.orders)){state.orders=d.orders;save();renderOrders(state.orders);renderProfile()}}catch(_){renderOrders(state.orders);if(state.orders.length)toast('Showing saved orders from this device.')}}
function startOrdersRefresh(){clearInterval(ordersRefreshTimer);ordersRefreshTimer=setInterval(()=>{if($('#ordersView')?.classList.contains('active-view'))loadOrders()},30000)}
function stopOrdersRefresh(){clearInterval(ordersRefreshTimer);ordersRefreshTimer=null}
function latestOrder(){return state.orders[0]||null}
function prefillCheckout(){const last=latestOrder(),saved=state.profile?.checkout||{},a=saved.address||last?.address||{};const fields=[['#customerName',saved.name||last?.customer?.name||''],['#customerPhone',saved.phone||last?.customer?.phone||''],['#house',a.house||''],['#area',a.area||''],['#city',a.city||''],['#pincode',a.pincode||''],['#landmark',a.landmark||''],['#note',a.note||'']];fields.forEach(([sel,val])=>{const el=$(sel);if(el&&!el.value)el.value=val})}
function setView(name){$('#confirmationView')?.remove();$$('.view').forEach(v=>v.classList.remove('active-view'));const view=$(`#${name}View`);if(!view)return;view.classList.add('active-view');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='orders'){renderOrders();loadOrders();startOrdersRefresh()}else stopOrdersRefresh();if(name==='cart')renderCart();if(name==='checkout'){prefillCheckout();updateCartBar()}if(name==='profile')renderProfile();window.scrollTo({top:0,behavior:'smooth'})}
function renderProfile(){const last=latestOrder(),name=$('#profileName'),phone=$('#profilePhone'),addr=$('#profileAddressText'),home=$('#homeAddress');if(name)name.textContent=state.profile?.checkout?.name||last?.customer?.name||'Guest customer';if(phone)phone.textContent=state.profile?.checkout?.phone||last?.customer?.phone||'Not signed in';if(addr)addr.textContent=state.profile.address||'Not saved yet';if(home)home.textContent=state.profile.address||'Add your delivery address'}
function changeQty(id,delta){const next=Number(state.cart[id]||0)+delta;if(delta>0&&next>99){toast('Maximum quantity is 99');return}if(next<=0)delete state.cart[id];else state.cart[id]=next;save();renderProducts($('#searchInput')?.value||'');if($('#cartView')?.classList.contains('active-view'))renderCart()}
function openAddressModal(){const m=$('#addressModal');if(m)m.classList.remove('hidden')}
function closeModal(){const m=$('#addressModal');if(m)m.classList.add('hidden')}
function checkoutClientId(data,address){const fingerprint=JSON.stringify({customer:data,address,items:cartItems().map(x=>({id:x.product.id,qty:x.qty}))});const saved=state.profile?.pendingCheckout;if(saved?.key&&saved.fingerprint===fingerprint)return saved.key;const key=(globalThis.crypto?.randomUUID?.()||`fw-${Date.now()}-${Math.random().toString(36).slice(2)}`).replace(/[^A-Za-z0-9_-]/g,'').slice(0,100);state.profile.pendingCheckout={key,fingerprint};save();return key}
async function submitOrder(e){e.preventDefault();if(!cartItems().length){toast('Your cart is empty');setView('home');return}const form=e.target,name=$('#customerName')?.value.trim()||'',phone=$('#customerPhone')?.value.trim()||'',address={house:$('#house')?.value.trim()||'',area:$('#area')?.value.trim()||'',city:$('#city')?.value.trim()||'',pincode:$('#pincode')?.value.trim()||'',landmark:$('#landmark')?.value.trim()||'',note:$('#note')?.value.trim()||''};if(name.length<2)return toast('Enter your full name');if(!/^\d{10}$/.test(phone))return toast('Enter a valid 10-digit mobile number');if(!address.house||!address.area||!address.city)return toast('Complete your delivery address');if(!/^\d{6}$/.test(address.pincode))return toast('Enter a valid 6-digit PIN code');const data={name,phone},clientOrderId=checkoutClientId(data,address),button=form.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Placing order…'}try{await window.FreshWayNotifications.ensureAuthenticated();const id=customerId();if(!id)throw new Error('Please log in before placing your order.');const result=await api('/api/orders',{method:'POST',body:JSON.stringify({customerId:id,clientOrderId,customer:data,address,items:cartItems().map(x=>({id:x.product.id,qty:x.qty})),whatsappOptIn:$('#whatsappOptIn')?.checked||false})});const order={id:result.id,customer:data,address,items:(result.items||[]).map(i=>({name:i.name,unit:i.unit,qty:i.qty,price:i.price,lineTotal:i.lineTotal})),total:result.total,payment:result.payment,status:result.status,deliveryPlan:result.deliveryPlan,createdAt:result.createdAt,updatedAt:result.updatedAt};state.orders=[order,...state.orders.filter(x=>x.id!==order.id)];state.cart={};state.profile.address=`${address.house}, ${address.area}, ${address.city} - ${address.pincode}`;state.profile.checkout={name,phone,address};delete state.profile.pendingCheckout;save();await window.FreshWayNotifications.registerCustomer(name,phone,$('#whatsappOptIn')?.checked||false);form.reset();renderProducts();renderProfile();showConfirmation(order)}catch(err){toast(err.message||'Could not place order. Your cart is still saved.')}finally{if(button){button.disabled=false;button.innerHTML='Place order · <span id="checkoutTotal">'+money(cartTotal())+'</span>'}updateCartBar()}}
function showConfirmation(order){const home=$('#homeView');if(!home)return;$('#confirmationView')?.remove();home.insertAdjacentHTML('afterend',`<section id="confirmationView" class="view active-view"><div class="empty" style="margin-top:20vh"><div style="font-size:55px">🎉</div><span class="eyebrow">ORDER PLACED</span><h1 style="font-size:25px;margin:8px 0">Thank you!</h1><p>Your order <strong>${esc(order.id)}</strong> has been placed successfully.</p><p class="muted">Payment: Cash · Delivery plan: ${esc(planText(order.deliveryPlan))}.</p><button class="primary-btn full" id="confirmationOrders">View my orders</button><button class="secondary-btn full" id="confirmationHome">Continue shopping</button></div></section>`);$$('.view').forEach(v=>{if(v.id!=='confirmationView')v.classList.remove('active-view')});$$('.nav-item').forEach(b=>b.classList.remove('active'));$('#confirmationOrders').onclick=()=>setView('orders');$('#confirmationHome').onclick=()=>setView('home');updateCartBar()}
async function loadProducts(){try{const d=await api('/api/products');if(Array.isArray(d.products)&&d.products.length)PRODUCTS=d.products}catch(_){}renderProducts($('#searchInput')?.value||'')}
document.addEventListener('click',e=>{const t=e.target;const add=t.closest('[data-add]'),plus=t.closest('[data-plus]'),minus=t.closest('[data-minus]');if(add)changeQty(add.dataset.add,1);if(plus)changeQty(plus.dataset.plus,1);if(minus)changeQty(minus.dataset.minus,-1);const nav=t.closest('[data-nav]');if(nav)setView(nav.dataset.nav);if(t.closest('#viewCartBtn'))setView('cart');if(t.closest('#checkoutBtn'))setView('checkout');if(t.closest('#addressBtn')||t.closest('#profileAddress'))openAddressModal();if(t.hasAttribute('data-close-modal'))closeModal();if(t.closest('#profileBtn'))setView('profile');if(t.closest('#brandHome'))setView('home');if(t.closest('.back-btn'))setView(t.closest('.back-btn').dataset.back);if(add||plus)toast('Added to cart')});
const searchInput=$('#searchInput');if(searchInput)searchInput.addEventListener('input',e=>renderProducts(e.target.value));
const checkoutForm=$('#checkoutForm');if(checkoutForm)checkoutForm.addEventListener('submit',submitOrder);
renderProducts();renderProfile();updateCartBar();loadProducts();loadOrders();