import original from './passcode-auth.js';

const COOKIE = 'freshway-admin-session';
const SESSION_HEADER = 'X-Freshway-Admin-Session';
const MAX_AGE = 60 * 60 * 8;
const WINDOW = 10 * 60;
const LIMIT = 10;
// Bump the namespace so stale login-limit rows from earlier releases cannot lock out the owner.
const RATE_KEY_PREFIX = 'admin:login:v3:';
const ADMIN_AUTH_VERSION = '2026-09-07-v4';
const enc = value => new TextEncoder().encode(value);
const hex = bytes => [...bytes].map(b => b.toString(16).padStart(2, '0')).join('');
const corsOrigin = env => { const value = String(env.APP_ORIGIN || '').trim(); return value && value !== 'https://YOUR-FRESHWAY-DOMAIN' ? value : 'null'; };
const ip = request => String(request.headers.get('CF-Connecting-IP') || request.headers.get('X-Forwarded-For') || 'unknown').split(',')[0].trim().slice(0, 80) || 'unknown';
async function key(env) { const secret = String(env.ADMIN_SESSION_SECRET || '').trim(); if (!secret) throw new Error('Admin session signing is not configured.'); return crypto.subtle.importKey('raw', enc(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); }
async function sign(env) { const issued = Math.floor(Date.now() / 1000); const payload = String(issued); const signature = await crypto.subtle.sign('HMAC', await key(env), enc(payload)); return `${payload}.${hex(new Uint8Array(signature))}`; }
function cookieValue(request) { const raw = request.headers.get('Cookie') || ''; const match = raw.match(new RegExp(`(?:^|;\\s*)${COOKIE}=([^;]+)`)); return match ? match[1] : ''; }
function sessionValue(request) { return cookieValue(request) || String(request.headers.get(SESSION_HEADER) || '').trim(); }
async function validSession(request, env) { const raw = sessionValue(request); if (!raw) return false; const [issuedRaw, signatureHex, ...extra] = raw.split('.'); if (extra.length) return false; const issued = Number(issuedRaw); if (!Number.isSafeInteger(issued) || !/^[0-9a-f]{64}$/i.test(signatureHex || '')) return false; const now = Math.floor(Date.now() / 1000); if (issued < now - MAX_AGE || issued > now + 60) return false; try { const expected = new Uint8Array(await crypto.subtle.sign('HMAC', await key(env), enc(issuedRaw))); const actual = new Uint8Array((signatureHex.match(/../g) || []).map(x => parseInt(x, 16))); if (actual.length !== expected.length) return false; let diff = 0; for (let i = 0; i < actual.length; i++) diff |= actual[i] ^ expected[i]; return diff === 0; } catch (_) { return false; } }
async function rateState(env, request) { const keyName = `${RATE_KEY_PREFIX}${ip(request)}`; const start = Math.floor(Date.now() / 1000 / WINDOW) * WINDOW; const row = await env.DB.prepare('SELECT count,window_start FROM auth_rate_limits WHERE key=?').bind(keyName).first(); if (!row || Number(row.window_start) !== start) return { allowed: true, retryAfter: 0, keyName, start }; const count = Number(row.count || 0); return { allowed: count < LIMIT, retryAfter: count >= LIMIT ? WINDOW - (Math.floor(Date.now() / 1000) - start) : 0, keyName, start }; }
async function recordFailure(env, state) { await env.DB.prepare(`INSERT INTO auth_rate_limits (key,window_start,count) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN auth_rate_limits.window_start=? THEN auth_rate_limits.count+1 ELSE 1 END, window_start=?, updated_at=CURRENT_TIMESTAMP`).bind(state.keyName, state.start, state.start, state.start).run(); }
async function clearFailures(env, state) { await env.DB.prepare('DELETE FROM auth_rate_limits WHERE key=?').bind(state.keyName).run(); }
async function sameSecret(a, b) { const [left, right] = await Promise.all([crypto.subtle.digest('SHA-256', enc(a)), crypto.subtle.digest('SHA-256', enc(b))]); const x = new Uint8Array(left), y = new Uint8Array(right); let diff = 0; for (let i = 0; i < x.length; i++) diff |= x[i] ^ y[i]; return diff === 0; }
function response(data, status, env, extra = {}) { return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': corsOrigin(env), 'access-control-allow-credentials': 'true', 'cache-control': 'private, no-store', ...extra } }); }
// The owner dashboard is hosted on pages.dev while the API is on workers.dev.
// SameSite=None is required for credentialed cross-site fetches; Secure is mandatory with it.
function withCookie(res, token) { const headers = new Headers(res.headers); headers.append('Set-Cookie', `${COOKIE}=${token}; Max-Age=${MAX_AGE}; Path=/; HttpOnly; Secure; SameSite=None`); headers.set('Cache-Control', 'private, no-store'); headers.set('Access-Control-Allow-Credentials', 'true'); return new Response(res.body, { status: res.status, statusText: res.statusText, headers }); }
export default { async fetch(request, env, ctx) { const url = new URL(request.url); const allowedOrigin = corsOrigin(env); const requestOrigin = String(request.headers.get('Origin') || '').trim(); if (requestOrigin && requestOrigin !== allowedOrigin) return response({ error: 'Origin not allowed.' }, 403, env); if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: { 'access-control-allow-origin': allowedOrigin, 'access-control-allow-methods': 'GET,POST,PATCH,OPTIONS', 'access-control-allow-headers': `Content-Type,Authorization,${SESSION_HEADER},X-Freshway-Admin-Token`, 'access-control-allow-credentials': 'true', 'access-control-expose-headers': 'Retry-After' } }); if (url.pathname === '/api/admin/status' && request.method === 'GET') return response({ ok: true, version: ADMIN_AUTH_VERSION }, 200, env); if (url.pathname === '/api/admin/login' && request.method === 'POST') { const state = await rateState(env, request); if (!state.allowed) return response({ error: 'Too many failed login attempts. Please wait a few minutes and try again.', retryAfter: state.retryAfter }, 429, env, { 'retry-after': String(Math.max(1, state.retryAfter)), 'access-control-expose-headers': 'Retry-After' }); let payload = {}; try { payload = await request.json(); } catch (_) {} const expected = String(env.ADMIN_TOKEN || '').trim(); const supplied = String(payload.token || '').trim(); if (!expected || !supplied || !(await sameSecret(supplied, expected))) { await recordFailure(env, state); return response({ error: 'Incorrect ADMIN_TOKEN. Please check it and try again.' }, 401, env); } await clearFailures(env, state); const session = await sign(env); return withCookie(response({ ok: true, version: ADMIN_AUTH_VERSION, session }, 200, env), session); } if (url.pathname === '/api/admin/logout' && request.method === 'POST') { const res = response({ ok: true }, 200, env); const headers = new Headers(res.headers); headers.append('Set-Cookie', `${COOKIE}=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=None`); return new Response(res.body, { status: res.status, headers }); } if (url.pathname.startsWith('/api/admin/') || url.pathname === '/api/notifications/broadcast') { if (!(await validSession(request, env))) return response({ error: 'Unauthorized' }, 401, env, { 'www-authenticate': 'Session' }); const headers = new Headers(request.headers); headers.set('Authorization', `Bearer ${String(env.ADMIN_TOKEN || '').trim()}`); headers.delete('X-Freshway-Admin-Token'); headers.delete(SESSION_HEADER); return original.fetch(new Request(request, { headers }), env, ctx); } return original.fetch(request, env, ctx); } };