export async function handleCatalogueRequest(request, env) {
  const url = new URL(request.url);
  const path = url.pathname;
  try {
    if (path === '/api/categories' && request.method === 'GET') return json(await publicCategories(env));
    if (path === '/api/products' && request.method === 'GET') return json(await publicProducts(env));
    if (path === '/api/admin/catalogue' && request.method === 'GET') return json(await adminCatalogue(env));
    if (path === '/api/admin/categories' && request.method === 'POST') return json(await createCategory(env, await readBody(request)), 201);
    if (path.startsWith('/api/admin/categories/') && request.method === 'PATCH') return json(await updateCategory(env, decodeURIComponent(path.split('/').pop()), await readBody(request)));
    if (path.startsWith('/api/admin/categories/') && request.method === 'DELETE') return json(await deleteCategory(env, decodeURIComponent(path.split('/').pop())));
    if (path === '/api/admin/catalogue/products' && request.method === 'POST') return json(await createProduct(env, await readBody(request)), 201);
    if (path.startsWith('/api/admin/catalogue/products/') && request.method === 'PATCH') return json(await updateProduct(env, decodeURIComponent(path.split('/').pop()), await readBody(request)));
    if (path.startsWith('/api/admin/catalogue/products/') && request.method === 'DELETE') return json(await deleteProduct(env, decodeURIComponent(path.split('/').pop())));
    return null;
  } catch (e) { return json({error:e?.message||'Catalogue request failed.'},400); }
}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
const readBody=async r=>{try{return await r.json()}catch(_){return{}}};
const clean=(v,max)=>String(v??'').trim().slice(0,max);
const slugify=v=>clean(v,80).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60);
const id=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
async function publicProducts(env){const {results}=await env.DB.prepare(`SELECT p.id,p.name,p.unit,p.price,p.emoji,p.active,p.category_id,p.display_order,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.active=1 AND c.active=1 ORDER BY c.display_order,c.name,p.display_order,p.name`).all();return{products:results||[]}}
async function publicCategories(env){const {results}=await env.DB.prepare(`SELECT c.id,c.name,c.slug,c.icon,c.description,c.display_order,COUNT(p.id) product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id AND p.active=1 WHERE c.active=1 GROUP BY c.id,c.name,c.slug,c.icon,c.description,c.display_order HAVING COUNT(p.id)>0 ORDER BY c.display_order ASC,c.name ASC`).all();return{categories:results||[]}}
async function adminCatalogue(env){const {results}=await env.DB.prepare(`SELECT c.id,c.name,c.slug,c.icon,c.description,c.display_order,c.active,COUNT(p.id) product_count,COALESCE(SUM(CASE WHEN p.active=1 THEN 1 ELSE 0 END),0) active_product_count,COALESCE(SUM(CASE WHEN p.active=0 THEN 1 ELSE 0 END),0) hidden_product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.id,c.name,c.slug,c.icon,c.description,c.display_order,c.active ORDER BY c.display_order ASC,c.name ASC`).all();const {results:products}=await env.DB.prepare(`SELECT p.id,p.name,p.unit,p.price,p.emoji,p.active,p.category_id,p.display_order,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY CASE WHEN c.display_order IS NULL THEN 999999 ELSE c.display_order END,c.name,p.display_order,p.name`).all();return{categories:results||[],products:products||[]}}
function validCategoryPayload(p){const name=clean(p.name,80);if(!name)throw new Error('Category name is required.');const slug=slugify(p.slug||name);if(!slug)throw new Error('Category slug is invalid.');return{name,slug,icon:clean(p.icon||'🛒',8),description:clean(p.description,240),displayOrder:Number.isInteger(Number(p.displayOrder))?Number(p.displayOrder):999,active:p.active===false?0:1}}
async function createCategory(env,p){const v=validCategoryPayload(p);const existing=await env.DB.prepare('SELECT id FROM categories WHERE slug=?').bind(v.slug).first();if(existing)throw new Error('A category with this name already exists.');const categoryId=id('cat');await env.DB.prepare('INSERT INTO categories (id,name,slug,icon,description,display_order,active) VALUES (?,?,?,?,?,?,?)').bind(categoryId,v.name,v.slug,v.icon,v.description,v.displayOrder,v.active).run();return{ok:true,category:{id:categoryId,...v,product_count:0,active_product_count:0,hidden_product_count:0}}}
async function updateCategory(env,categoryId,p){const current=await env.DB.prepare('SELECT * FROM categories WHERE id=?').bind(categoryId).first();if(!current)throw new Error('Category not found.');const v=validCategoryPayload({...current,...p});const existing=await env.DB.prepare('SELECT id FROM categories WHERE slug=? AND id<>?').bind(v.slug,categoryId).first();if(existing)throw new Error('A category with this name already exists.');await env.DB.prepare('UPDATE categories SET name=?,slug=?,icon=?,description=?,display_order=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(v.name,v.slug,v.icon,v.description,v.displayOrder,v.active,categoryId).run();return{ok:true}}
async function deleteCategory(env,categoryId){const current=await env.DB.prepare('SELECT id FROM categories WHERE id=?').bind(categoryId).first();if(!current)throw new Error('Category not found.');const used=Number((await env.DB.prepare('SELECT COUNT(*) count FROM products WHERE category_id=?').bind(categoryId).first())?.count||0);if(used)throw new Error('This category contains products. Hide the category instead of deleting it.');await env.DB.prepare('DELETE FROM categories WHERE id=?').bind(categoryId).run();return{ok:true}}
async function requireCategory(env,categoryId){const c=await env.DB.prepare('SELECT id,name,active FROM categories WHERE id=?').bind(clean(categoryId,100)).first();if(!c)throw new Error('Select a valid category.');return c}
const units=new Set(['kg','g','litre','ml','piece','packet','box','bottle','dozen']);
async function createProduct(env,p){const name=clean(p.name,100),unit=clean(p.unit,30),price=Number(p.price),emoji=clean(p.emoji||'🛒',8),categoryId=clean(p.categoryId,100),displayOrder=Number.isInteger(Number(p.displayOrder))?Number(p.displayOrder):999;if(!name||!unit||!Number.isFinite(price)||price<0)throw new Error('Product name, unit and valid price are required.');if(!units.has(unit))throw new Error('Select a valid unit.');await requireCategory(env,categoryId);const productId=id('p');await env.DB.prepare('INSERT INTO products (id,name,unit,price,emoji,active,category_id,display_order) VALUES (?,?,?,?,?,?,?,?)').bind(productId,name,unit,Math.round(price),emoji,1,categoryId,displayOrder).run();return{ok:true,product:{id:productId,name,unit,price:Math.round(price),emoji,active:1,category_id:categoryId,display_order:displayOrder}}}
async function updateProduct(env,productId,p){const current=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(productId).first();if(!current)throw new Error('Product not found.');const next={...current,...p};const name=clean(next.name,100),unit=clean(next.unit,30),price=Number(next.price),emoji=clean(next.emoji||'🛒',8),categoryId=clean(next.categoryId||next.category_id,100),displayOrder=Number.isInteger(Number(next.displayOrder??next.display_order))?Number(next.displayOrder??next.display_order):999;if(!name||!unit||!Number.isFinite(price)||price<0)throw new Error('Enter a valid name, price and unit.');if(!units.has(unit))throw new Error('Select a valid unit.');await requireCategory(env,categoryId);await env.DB.prepare('UPDATE products SET name=?,unit=?,price=?,emoji=?,active=?,category_id=?,display_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(name,unit,Math.round(price),emoji,next.active?1:0,categoryId,displayOrder,productId).run();return{ok:true}}
async function deleteProduct(env,productId){const used=Number((await env.DB.prepare('SELECT COUNT(*) count FROM order_items WHERE product_id=?').bind(productId).first())?.count||0);if(used)throw new Error('This product is part of existing orders. Hide it instead of deleting it.');const result=await env.DB.prepare('DELETE FROM products WHERE id=?').bind(productId).run();if(!result.meta?.changes)throw new Error('Product not found.');return{ok:true}}
