const assert=require('node:assert/strict');
const vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(require('node:fs').readFileSync('frontend/customer/address-flow.js','utf8'),context);
const api=context.window.FreshWayCustomerAddressFlow;
assert.deepEqual(Array.from(api.fields),['house','area','city','pincode','landmark','note']);
const values={house:'12',area:'Main Road',city:'Warangal',pincode:'506001',landmark:'Temple',note:'Call first'};
const nodes=Object.fromEntries(Object.entries(values).map(([id,value])=>[id,{value}]));
const document={querySelector(selector){return nodes[selector.slice(1)]||null}};
const addressApi={normalize(value){return {...value,normalized:true}}};
assert.equal(api.read(document,addressApi).normalized,true);
assert.equal(api.read(document,addressApi).house,'12');
api.fill(document,{house:'99',area:'New Area',city:'Hyderabad',pincode:'500001',landmark:'',note:'Later'});
assert.equal(nodes.house.value,'99');
assert.equal(nodes.city.value,'Hyderabad');
assert.equal(nodes.note.value,'Later');
nodes.house.value='existing';
api.fill(document,{house:'replacement',area:'X',city:'Y',pincode:'123456',landmark:'Z',note:'N'},{onlyEmpty:true});
assert.equal(nodes.house.value,'existing');
assert.equal(nodes.area.value,'X');
console.log('customer address flow OK');
