const assert=require('node:assert/strict');
const vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(require('node:fs').readFileSync('frontend/customer/cart-actions.js','utf8'),context);
const api=context.window.FreshWayCustomerCartActions;
assert.equal(typeof api.bind,'function');
const listeners={};
const document={__freshwayCartActionsBound:false,addEventListener(type,fn){listeners[type]=fn}};
const calls=[];
const toastCalls=[];
api.bind({document,changeQty:(id,delta)=>calls.push([id,delta]),toast:msg=>toastCalls.push(msg)});
assert.equal(typeof listeners.click,'function');
listeners.click({target:{closest:s=>s==='[data-add]'?{dataset:{add:'apple'}}:null}});
assert.deepEqual(calls,[['apple',1]]);
assert.deepEqual(toastCalls,['Added to cart']);
listeners.click({target:{closest:s=>s==='[data-plus]'?{dataset:{plus:'banana'}}:null}});
assert.deepEqual(calls,[['apple',1],['banana',1]]);
listeners.click({target:{closest:s=>s==='[data-minus]'?{dataset:{minus:'orange'}}:null}});
assert.deepEqual(calls,[['apple',1],['banana',1],['orange',-1]]);
api.bind({document,changeQty:()=>{throw new Error('duplicate bind')}});
console.log('customer cart actions OK');
