const assert=require('node:assert/strict');
const vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(require('node:fs').readFileSync('frontend/customer/cart-actions.js','utf8'),context);
const api=context.window.FreshWayCustomerCartActions;
assert.equal(typeof api.bind,'function');
const listeners={};
const document={__freshwayCartActionsBound:false,addEventListener(type,fn){listeners[type]=fn}};
const calls=[];
const toastCalls=[];
api.bind({document,changeQty:(id,delta)=>calls.push([id,delta]),toast:msg=>toastCalls.push(msg)});
assert.equal(typeof listeners.click,'function');
const target=(selector)=>({closest:s=>s===selector?{dataset:{add:'apple',plus:'banana',minus:'orange'}[s.slice(7)]}:null});
listeners.click({target:target('[data-add]')});
assert.deepEqual(calls,[['apple',1]]);
assert.deepEqual(toastCalls,['Added to cart']);
const targetMinus={closest:s=>s==='[data-minus]'?{dataset:{minus:'orange'}}:null};
listeners.click({target:targetMinus});
assert.deepEqual(calls,[['apple',1],['orange',-1]]);
api.bind({document,changeQty:()=>{throw new Error('duplicate bind')}});
console.log('customer cart actions OK');
