const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(fs.readFileSync('frontend/customer/cart-bar.js','utf8'),context);
const api=context.window.FreshWayCustomerCartBar;
assert.equal(typeof api.update,'function');
const nodes={};
for(const id of ['cartCount','cartTotal','cartBadge','cartBar','checkoutTotal'])nodes[id]={textContent:'',classList:{hidden:false,toggle(name,value){this[name]=value}}};
const document={querySelector(selector){return nodes[selector.slice(1)]||null}};
api.update(document,{count:2,total:240,money:n=>`₹${n}`});
assert.equal(nodes.cartCount.textContent,'2 items');
assert.equal(nodes.cartTotal.textContent,'₹240');
assert.equal(nodes.cartBadge.textContent,2);
assert.equal(nodes.cartBadge.classList.hidden,false);
assert.equal(nodes.cartBar.classList.hidden,false);
assert.equal(nodes.checkoutTotal.textContent,'₹240');
api.update(document,{count:0,total:0,money:n=>`₹${n}`});
assert.equal(nodes.cartCount.textContent,'0 items');
assert.equal(nodes.cartBadge.classList.hidden,true);
assert.equal(nodes.cartBar.classList.hidden,true);
console.log('customer cart bar OK');
