const assert=require('node:assert/strict');
const vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(require('node:fs').readFileSync('frontend/customer/keyboard.js','utf8'),context);
const api=context.window.FreshWayCustomerKeyboard;
assert.equal(typeof api.bind,'function');
let handler;
const brand={addEventListener(type,fn){assert.equal(type,'keydown');handler=fn}};
const document={__freshwayKeyboardBound:false,querySelector(selector){assert.equal(selector,'#brandHome');return brand}};
let homeCalls=0;
api.bind({document,onHome:()=>homeCalls++});
assert.equal(document.__freshwayKeyboardBound,true);
handler({key:'Enter',preventDefault(){this.prevented=true}});
assert.equal(homeCalls,1);
handler({key:' ',preventDefault(){this.prevented=true}});
assert.equal(homeCalls,2);
handler({key:'Escape',preventDefault(){throw new Error('should not prevent')}});
assert.equal(homeCalls,2);
api.bind({document,onHome:()=>{throw new Error('duplicate bind')}});
console.log('customer keyboard helpers OK');
