(function(){
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const api=async(path,opt={})=>{const s=sessionStorage.getItem('freshway-admin-session')||'',h={'Content-Type':'application/json',...(opt.headers||{})};if(s)h['X-Freshway-Admin-Session']=s;const r=await fetch(`/api${path}`,{...opt,credentials:'include',headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d};
  let data={categories:[],products:[]},selected=null;
  const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
  function shell(){const host=$('#catalogue');if(!host||host.dataset.fwCatalogueReady)return;host.dataset.fwCatalogueReady='1';host.innerHTML=`<div class="page-head"><div><span class="eyebrow">PRODUCTS</span><h1>Catalogue</h1><p>Manage categories and customer products independently.</p></div><button id="catAddProduct" class="primary">+ Add product</button></div><div id="catCategories" class="cards"></div><div id="catProducts" class="hidden"></div>`;}
  function categoryCard(c){return`<article class="card"><div class="card-top"><div><b>${esc(c.icon)} ${esc(c.name)}</b><small>${esc(c.description||'')}</small></div><span class="badge ${c.active?'good':'hidden-state'}">${c.active?'Active':'Hidden'}</span></div><div class="meta">${Number(c.active_product_count||0)} active · ${Number(c.hidden_product_count||0)} hidden</div><div class="card-foot"><button class="ghost" data-cat-open="${esc(c.id)}">Manage products</button><button class="ghost" data-cat-edit="${esc(c.id)}">Edit</button><button class="ghost" data-cat-toggle="${esc(c.id)}" data-active="${c.active?1:0}">${c.active?'Hide':'Show'}</button><button class="ghost" data-cat-delete="${esc(c.id)}">Delete</button></div></article>`}
  function productCard(p){return`<article class="product-card"><div class="product-icon">${esc(p.emoji||'🛒')}</div><b>${esc(p.name)}</b><span>${money(p.price)} / ${esc(p.unit)}</span><small>${esc(p.category_name||'Uncategorised')} · <span class="${p.active?'available':'hidden-state'}">● ${p.active?'Available':'Hidden'}</span></small><div><button class="ghost" data-p-edit="${esc(p.id)}">Edit</button><button class="ghost" data-p-toggle="${esc(p.id)}" data-active="${p.active?1:0}">${p.active?'Hide':'Show'}</button><button class="ghost" data-p-delete="${esc(p.id)}">Delete</button></div></article>`}
  function render(){shell();const cats=$('#catCategories'),prods=$('#catProducts');if(!cats||!prods)return;if(selected){const c=data.categories.find(x=>x.id===selected);cats.innerHTML=`<div class="section-head"><div><span class="eyebrow">CATEGORY</span><h2>${esc(c?.icon||'🛒')} ${esc(c?.name||'Category')}</h2><p>${Number(c?.product_count||0)} total products.</p></div><button class="ghost" data-cat-back>← All categories</button></div><div class="toolbar"><button class="primary" data-cat-add-product="${esc(selected)}">+ Add product</button></div><div class="product-grid">${data.products.filter(p=>p.category_id===selected).map(productCard).join('')||'<div class="empty">No products in this category yet.</div>'}</div>`;cats.classList.add('hidden');prods.classList.remove('hidden');prods.innerHTML='';return}cats.classList.remove('hidden');prods.classList.add('hidden');cats.innerHTML=`<div class="section-head"><div><span class="eyebrow">CATEGORIES</span><h2>Shop categories</h2><p>Categories are customer-facing and database controlled.</p></div><button class="primary" id="catAddCategory">+ Add category</button></div><div class="card-grid">${data.categories.map(categoryCard).join('')||'<div class="empty">No categories yet.</div>'}</div>`}
  async function load(){try{data=await api('/admin/catalogue');render()}catch(e){if(typeof window.toast==='function')window.toast(e.message)}}
  async function mutate(path,method,payload){try{await api(path,{method,body:JSON.stringify(payload||{})});await load();if(typeof window.toast==='function')window.toast('Catalogue updated')}catch(e){if(typeof window.toast==='function')window.toast(e.message)}}
  function openCategoryForm(id){const c=id?data.categories.find(x=>x.id===id):null;const name=prompt('Category name',c?.name||'');if(!name?.trim())return;const icon=prompt('Category icon / emoji',c?.icon||'🛒');const description=prompt('Short description',c?.description||'');const displayOrder=prompt('Display order',String(c?.display_order??999));mutate(id?`/admin/categories/${encodeURIComponent(id)}`:'/admin/categories',id?'PATCH':'POST',{name:name.trim(),icon:icon||'🛒',description:description||'',displayOrder:Number(displayOrder||999),active:c?!!c.active:true})}
  function openProductForm(categoryId,id){const p=id?data.products.find(x=>x.id===id):null;const name=prompt('Product name',p?.name||'');if(!name?.trim())return;const price=prompt('Price',String(p?.price??''));const unit=prompt('Unit (kg, g, litre, ml, piece, packet, box, bottle, dozen)',p?.unit||'');const emoji=prompt('Emoji',p?.emoji||'🛒');const order=prompt('Display order',String(p?.display_order??999));mutate(id?`/admin/catalogue/products/${encodeURIComponent(id)}`:'/admin/catalogue/products',id?'PATCH':'POST',{name:name.trim(),price:Number(price),unit:unit?.trim(),emoji:emoji||'🛒',categoryId:categoryId||p?.category_id,displayOrder:Number(order||999),active:p?!!p.active:true})}
  function install(){document.addEventListener('click',e=>{const s=e.target.closest('[data-screen]');if(s)return;const b=e.target.closest('[data-cat-open]');if(b){selected=b.dataset.catOpen;render();return}if(e.target.closest('[data-cat-back]')){selected=null;render();return}const ce=e.target.closest('[data-cat-edit]');if(ce){openCategoryForm(ce.dataset.catEdit);return}const ct=e.target.closest('[data-cat-toggle]');if(ct){mutate(`/admin/categories/${encodeURIComponent(ct.dataset.catToggle)}`,'PATCH',{active:ct.dataset.active!=='1'});return}const cd=e.target.closest('[data-cat-delete]');if(cd&&confirm('Delete this empty category?'))mutate(`/admin/categories/${encodeURIComponent(cd.dataset.catDelete)}`,'DELETE');const ca=e.target.closest('#catAddCategory');if(ca){openCategoryForm();return}const cap=e.target.closest('[data-cat-add-product]');if(cap){openProductForm(cap.dataset.catAddProduct);return}const pe=e.target.closest('[data-p-edit]');if(pe){openProductForm(selected,pe.dataset.pEdit);return}const pt=e.target.closest('[data-p-toggle]');if(pt){mutate(`/admin/catalogue/products/${encodeURIComponent(pt.dataset.pToggle)}`,'PATCH',{active:pt.dataset.active!=='1'});return}const pd=e.target.closest('[data-p-delete]');if(pd&&confirm('Delete this product?'))mutate(`/admin/catalogue/products/${encodeURIComponent(pd.dataset.pDelete)}`,'DELETE');});
    const base=window.navigateAdminScreen;
    if(typeof base==='function'&&!base.__fwCatalogueWrapped){const wrapped=function(id){base(id);if(id==='catalogue'){selected=null;shell();load()}};wrapped.__fwCatalogueWrapped=true;window.navigateAdminScreen=wrapped}
    const add=$('#catAddProduct');if(add)add.onclick=()=>openProductForm(selected);if(location.hash.slice(1)==='catalogue'){shell();load()}
    const loader=document.createElement('script');loader.src='frontend/admin/push.js?v=20260908-push-v1';loader.async=false;document.head.appendChild(loader);
  }
  install();
})();
