(function(){
  const SESSION_KEY='freshway-admin-session';
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
  const session=()=>{try{return sessionStorage.getItem(SESSION_KEY)||''}catch(_){return''}};
  async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})},s=session();if(s)headers['X-Freshway-Admin-Session']=s;const r=await fetch(`/api${path}`,{...opt,credentials:'include',headers});const d=await r.json().catch(()=>({error:`Request failed (${r.status})`}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
  let data={categories:[],products:[]},selected=null,loading=false;
  const style=document.createElement('style');style.textContent=`#catalogue .fw-cat-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.fw-category-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.fw-category-card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:15px}.fw-cat-main{display:flex;gap:12px;align-items:flex-start}.fw-cat-icon{width:48px;height:48px;border-radius:14px;background:var(--mint);display:grid;place-items:center;font-size:25px;flex:0 0 auto}.fw-cat-main b,.fw-cat-main small{display:block}.fw-cat-main b{font-size:14px}.fw-cat-main small{font-size:9px;color:var(--muted);margin-top:4px}.fw-cat-count{margin-left:auto;font-size:9px;font-weight:900;color:var(--g);white-space:nowrap}.fw-cat-actions,.fw-product-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.fw-cat-actions button,.fw-product-actions button{font-size:9px}.fw-products-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:20px 0 12px}.fw-products-head h2{margin:0;font-size:18px}.fw-products-head small{display:block;color:var(--muted);font-size:9px;margin-top:3px}.fw-products{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.fw-product{background:#fff;border:1px solid var(--line);border-radius:15px;padding:14px}.fw-product-icon{height:70px;border-radius:12px;background:#f4f8f5;display:grid;place-items:center;font-size:34px}.fw-product b,.fw-product span,.fw-product small{display:block}.fw-product b{font-size:11px;margin-top:9px}.fw-product span{font-size:10px;color:var(--muted);margin-top:3px}.fw-product small{font-size:9px;font-weight:900;margin-top:7px}.fw-product .good{color:var(--g)}.fw-product .bad{color:var(--red)}.fw-empty{background:#fff;border:1px dashed #ccd9d1;border-radius:14px;padding:28px;text-align:center;color:var(--muted);font-size:10px;grid-column:1/-1}.fw-modal{position:fixed;inset:0;background:rgba(9,29,20,.46);display:grid;place-items:center;padding:15px;z-index:80}.fw-modal-card{background:#fff;border-radius:20px;width:min(520px,100%);max-height:90vh;overflow:auto;padding:22px;position:relative}.fw-modal-card h2{margin:4px 0 16px;font-size:20px}.fw-close{position:absolute;right:15px;top:15px;border:0;background:#f1f5f2;border-radius:9px;width:32px;height:32px;font-size:19px}.fw-modal-card label{display:block;font-size:9px;font-weight:900;margin:0 0 10px}.fw-modal-card input,.fw-modal-card textarea,.fw-modal-card select{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;background:#fff;font:inherit;font-size:10px;margin-top:5px}.fw-two{display:grid;grid-template-columns:1fr 1fr;gap:8px}@media(max-width:800px){.fw-category-list{grid-template-columns:1fr}.fw-products{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.fw-products{grid-template-columns:1fr}.fw-two{grid-template-columns:1fr}}`;document.head.appendChild(style);
  function toast(m){const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');clearTimeout(window.__fwCatToast);window.__fwCatToast=setTimeout(()=>t.classList.remove('show'),2600)}}
  function shell(){const s=$('#catalogue');if(!s)return null;s.innerHTML=`<div class="page-head"><div><span class="eyebrow">CATALOGUE</span><h1>Catalogue</h1><p>Manage categories and the products customers can order.</p></div><button id="fwAddCategory" class="primary">+ Add category</button></div><div class="fw-cat-toolbar"><button id="fwAllCategories" class="ghost">All categories</button><button id="fwRefreshCatalogue" class="ghost">↻ Refresh</button></div><div id="fwCategoryList" class="fw-category-list"></div><div id="fwProductsArea"></div>`;return s}
  function openModal(html){let m=$('#fwCatalogueModal');if(!m){m=document.createElement('div');m.id='fwCatalogueModal';m.className='fw-modal';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.remove()})}m.innerHTML=`<div class="fw-modal-card">${html}</div>`;return m}
  function closeModal(){const m=$('#fwCatalogueModal');if(m)m.remove()}
  function categoryById(id){return data.categories.find(c=>String(c.id)===String(id))}
  function renderProducts(){const area=$('#fwProductsArea');if(!area)return;const c=categoryById(selected);if(!c){area.innerHTML='<div class="fw-empty" style="margin-top:14px">Select a category to manage its products.</div>';return}const ps=data.products.filter(p=>String(p.category_id)===String(c.id));area.innerHTML=`<div class="fw-products-head"><div><h2>${esc(c.icon)} ${esc(c.name)}</h2><small>${c.active_product_count} active products · ${c.hidden_product_count} hidden</small></div><button id="fwAddProduct" class="primary">+ Add product</button></div><div class="fw-products">${ps.length?ps.map(p=>`<article class="fw-product"><div class="fw-product-icon">${esc(p.emoji)}</div><b>${esc(p.name)}</b><span>${money(p.price)} / ${esc(p.unit)}</span><small class="${p.active?'good':'bad'}">● ${p.active?'Available':'Hidden'} · order ${Number(p.display_order||999)}</small><div class="fw-product-actions"><button class="ghost" data-fw-edit-product="${esc(p.id)}">Edit</button><button class="ghost" data-fw-toggle-product="${esc(p.id)}">${p.active?'Hide':'Show'}</button><button class="ghost fw-danger" data-fw-delete-product="${esc(p.id)}">Delete</button></div></article>`).join(''):'<div class="fw-empty">No products in this category yet.<br>Use <strong>+ Add product</strong> to add the first item.</div>'}</div>`}
  function render(){shell();const list=$('#fwCategoryList');if(!list)return;list.innerHTML=data.categories.length?data.categories.map(c=>`<article class="fw-category-card"><div class="fw-cat-main"><div class="fw-cat-icon">${esc(c.icon)}</div><div><b>${esc(c.name)}</b><small>${esc(c.description||'')}</small></div><span class="fw-cat-count">${c.active_product_count} active · ${c.hidden_product_count} hidden</span></div><div class="fw-cat-actions"><button class="primary" data-fw-manage="${esc(c.id)}">Manage products</button><button class="ghost" data-fw-edit-cat="${esc(c.id)}">Edit</button><button class="ghost" data-fw-toggle-cat="${esc(c.id)}">${c.active?'Hide':'Show'}</button><button class="ghost fw-danger" data-fw-delete-cat="${esc(c.id)}">Delete</button></div></article>`).join(''):'<div class="fw-empty"><strong>No categories yet.</strong><br>Create the first catalogue category.</div>';renderProducts()}
  async function load(){if(loading)return;loading=true;try{data=await api('/admin/catalogue');render()}catch(e){toast(e.message)}finally{loading=false}}
  function categoryForm(c){const edit=!!c;openModal(`<button class="fw-close" data-fw-close>×</button><span class="eyebrow">CATALOGUE CATEGORY</span><h2>${edit?'Edit category':'Add category'}</h2><form id="fwCategoryForm" data-category-id="${esc(c?.id||'')}"><label>Category name<input id="fwCatName" required maxlength="80" value="${esc(c?.name||'')}"></label><label>Icon / emoji<input id="fwCatIcon" maxlength="8" value="${esc(c?.icon||'🛒')}"></label><label>Description<input id="fwCatDesc" maxlength="240" value="${esc(c?.description||'')}"></label><div class="fw-two"><label>Display order<input id="fwCatOrder" type="number" min="1" value="${Number(c?.display_order||999)}"></label><label>Status<select id="fwCatActive"><option value="1" ${c?.active!==0?'selected':''}>Active</option><option value="0" ${c?.active===0?'selected':''}>Hidden</option></select></label></div><button class="primary full" type="submit">${edit?'Save changes':'Create category'}</button></form>`)}
  function productForm(p){const c=categoryById(p?.category_id)||categoryById(selected);openModal(`<button class="fw-close" data-fw-close>×</button><span class="eyebrow">${esc(c?.name||'CATEGORY')}</span><h2>${p?'Edit product':'Add product'}</h2><form id="fwProductForm" data-product-id="${esc(p?.id||'')}"><label>Product name<input id="fwPName" required maxlength="100" value="${esc(p?.name||'')}"></label><label>Category<select id="fwPCat" required>${data.categories.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(c?.id)?'selected':''}>${esc(x.icon)} ${esc(x.name)}</option>`).join('')}</select></label><div class="fw-two"><label>Price (₹)<input id="fwPPrice" required type="number" min="0" value="${p?.price??''}"></label><label>Unit<select id="fwPUnit" required>${['kg','g','litre','ml','piece','packet','box','bottle','dozen'].map(u=>`<option value="${u}" ${u===p?.unit?'selected':''}>${u}</option>`).join('')}</select></label></div><label>Icon / emoji<input id="fwPEmoji" maxlength="8" value="${esc(p?.emoji||'🛒')}"></label><div class="fw-two"><label>Display order<input id="fwPOrder" type="number" min="1" value="${Number(p?.display_order||999)}"></label><label>Status<select id="fwPActive"><option value="1" ${p?.active!==0?'selected':''}>Available</option><option value="0" ${p?.active===0?'selected':''}>Hidden</option></select></label></div><button class="primary full" type="submit">${p?'Save changes':'Add product'}</button></form>`)}
  async function saveCategory(e,c){e.preventDefault();const payload={name:$('#fwCatName').value.trim(),icon:$('#fwCatIcon').value.trim()||'🛒',description:$('#fwCatDesc').value.trim(),displayOrder:Number($('#fwCatOrder').value)||999,active:$('#fwCatActive').value==='1'};try{await api(c?`/admin/categories/${encodeURIComponent(c.id)}`:'/admin/categories',{method:c?'PATCH':'POST',body:JSON.stringify(payload)});closeModal();await load();toast(c?'Category updated':'Category created')}catch(x){toast(x.message)}}
  async function saveProduct(e,p){e.preventDefault();const payload={name:$('#fwPName').value.trim(),categoryId:$('#fwPCat').value,price:Number($('#fwPPrice').value),unit:$('#fwPUnit').value,emoji:$('#fwPEmoji').value.trim()||'🛒',displayOrder:Number($('#fwPOrder').value)||999,active:$('#fwPActive').value==='1'};try{await api(p?`/admin/catalogue/products/${encodeURIComponent(p.id)}`:'/admin/catalogue/products',{method:p?'PATCH':'POST',body:JSON.stringify(payload)});closeModal();selected=payload.categoryId;await load();toast(p?'Product updated':'Product added')}catch(x){toast(x.message)}}
  async function mutate(path,method,payload,msg){try{await api(path,{method,body:payload?JSON.stringify(payload):undefined});await load();toast(msg)}catch(e){toast(e.message)}}
  function install(){
    const baseNavigate=window.navigateAdminScreen;
    if(typeof baseNavigate!=='function')return;
    window.navigateAdminScreen=function(id){const result=baseNavigate(id);if(id==='catalogue'){selected=null;shell();load()}return result};
    document.addEventListener('click',e=>{const target=e.target;const b=target.closest('[data-fw-manage]');if(b){selected=b.dataset.fwManage;render();return}if(target.closest('#fwAddCategory')){categoryForm();return}if(target.closest('#fwRefreshCatalogue')){load();return}if(target.closest('#fwAllCategories')){selected=null;render();return}if(target.closest('#fwAddProduct')){productForm();return}const ec=target.closest('[data-fw-edit-cat]');if(ec){categoryForm(categoryById(ec.dataset.fwEditCat));return}const tc=target.closest('[data-fw-toggle-cat]');if(tc){const c=categoryById(tc.dataset.fwToggleCat);if(c)mutate(`/admin/categories/${encodeURIComponent(c.id)}`,'PATCH',{name:c.name,icon:c.icon,description:c.description,displayOrder:c.display_order,active:!c.active},'Category updated');return}const dc=target.closest('[data-fw-delete-cat]');if(dc){const c=categoryById(dc.dataset.fwDeleteCat);if(c&&confirm(`Delete ${c.name}? Categories containing products cannot be deleted.`))mutate(`/admin/categories/${encodeURIComponent(c.id)}`,'DELETE',null,'Category deleted');return}const ep=target.closest('[data-fw-edit-product]');if(ep){const p=data.products.find(x=>String(x.id)===String(ep.dataset.fwEditProduct));if(p)productForm(p);return}const tp=target.closest('[data-fw-toggle-product]');if(tp){const p=data.products.find(x=>String(x.id)===String(tp.dataset.fwToggleProduct));if(p)mutate(`/admin/catalogue/products/${encodeURIComponent(p.id)}`,'PATCH',{name:p.name,categoryId:p.category_id,price:p.price,unit:p.unit,emoji:p.emoji,displayOrder:p.display_order,active:!p.active},'Product updated');return}const dp=target.closest('[data-fw-delete-product]');if(dp){const p=data.products.find(x=>String(x.id)===String(dp.dataset.fwDeleteProduct));if(p&&confirm(`Delete ${p.name}? This cannot be undone.`))mutate(`/admin/catalogue/products/${encodeURIComponent(p.id)}`,'DELETE',null,'Product deleted');return}if(target.closest('[data-fw-close]'))closeModal()},false);
    document.addEventListener('submit',e=>{if(e.target.id==='fwCategoryForm'){const cid=e.target.dataset.categoryId||'';saveCategory(e,data.categories.find(x=>String(x.id)===String(cid))||null)}if(e.target.id==='fwProductForm'){const pid=e.target.dataset.productId||'';saveProduct(e,data.products.find(x=>String(x.id)===String(pid))||null)}},true);
  }
  install();
  const pushLoader=document.createElement('script');pushLoader.src='frontend/admin/push.js?v=20260908-push-v1';pushLoader.async=false;document.head.appendChild(pushLoader);
})();
